import Ai from "./components/Ai";
export default function App() {
  return (
    <div className="m-10 p-5 border-1 rounded-lg border-gray-200 shadow-white grid grid-cols-1 sm:grid-cols-2  md:grid-cols-3 lg:grid-cols-4 gap-4">
      <Ai
        name="ChatGpt"
        logo="https://img.utdstc.com/icon/9c5/5ec/9c55eca10f08761429d2b7b977c7aafc3c09789a9d1ec945d814d7de9d2b0203:200"
        link="https://chat.openai.com/"
      />
      <Ai
        name="DeepSeek"
        logo={"https://pipedream.com/s.v0/app_Rphvnx/logo/orig"}
        link={"https://chat.deepseek.com/"}
      />
      <Ai
        name="Gemini"
        logo="https://img.utdstc.com/icon/38b/89a/38b89a668208de992e59fe9941d9f1f4a5e2febe97e4d36039c85250b6675904:200"
        link="https://gemini.google.com/app"
      />
      <Ai
        name="MetaAi"
        logo={
          "https://zorgle.co.uk/wp-content/uploads/2024/11/Meta-ai-logo.png"
        }
        link="https://www.meta.ai/"
      />
      <Ai
        name="Claude"
        logo="https://images.seeklogo.com/logo-png/55/2/claude-logo-png_seeklogo-554540.png"
        link="https://claude.ai"
      />
      <Ai
        name="Copilot"
        logo="https://oit.duke.edu/sites/default/files/styles/scale_width_500/public/Copilot%20icon.png?itok=uR_Q2jZa"
        link="https://copilot.microsoft.com/"
      />
      <Ai
        name="LeChat"
        logo="https://play-lh.googleusercontent.com/TMRXNJnv0fN8wEkH6-GHE-7V8w-7IfPetHVTcPf5cu2vgv6EAEjzbgklrYzDKnHZZNo=w240-h480-rw"
        link="https://chat.mistral.ai/chat"
      />
      <Ai
        name="Perplexity"
        logo="https://images.seeklogo.com/logo-png/51/2/perplexity-ai-logo-png_seeklogo-517845.png"
        link="https://www.perplexity.ai"
      />
      <Ai
        name="Grok"
        logo="https://images.seeklogo.com/logo-png/49/2/xai-logo-png_seeklogo-491313.png"
        link="https://x.ai/"
      />
      <Ai
        name="Kimi"
        logo="https://images.sftcdn.net/images/t_app-icon-m/p/72179877-b940-4b95-816b-c6761ee5d19b/4286187142/kimi-ai-ce-bian-lan-zhu-shou-logo"
        link="https://kimi.moonshot.cn"
      />
      <Ai
        name="You"
        logo="https://play-lh.googleusercontent.com/QiocnvgPQ7NK1c8mEWzo6f3UhFjvq4-grZgkwz1XlMDnDKJz_84EW8gtdvd5XYw62LM"
        link="https://you.com"
      />
      <Ai
        name="HuggingChat"
        logo="https://huggingface.co/datasets/huggingface/brand-assets/resolve/main/hf-logo.svg"
        link="https://huggingface.co/chat"
      />
      <Ai
        name="Pi"
        logo="https://play-lh.googleusercontent.com/Ef7is-Xonqhs2agdsGarpTS_c1Is6Yvk-JhnL3qNvU1Nwdc7kn6Dml2IuCqlfa9Nuzk"
        link="https://pi.ai"
      />
      <Ai
        name="ChatLLM"
        logo="https://play-lh.googleusercontent.com/O35u7LcmgKHsRpEQvHmT9ACfvDvP5S6HRIVmz-x-spUhojXIcnk0wbMEqaBSWPUJYQ"
        link="https://chatllm.abacus.ai/"
      />
      <Ai
        name="Qwen"
        logo="https://images.seeklogo.com/logo-png/61/1/qwen-icon-logo-png_seeklogo-611724.png"
        link="https://chat.qwenlm.ai/"
      />
      <Ai
        name="BlackBox"
        logo="https://play-lh.googleusercontent.com/Z_fquqqNzAd8FkpSjlnURnMtmLh8HRf_h_kIwhs0NbXKpO4WZ_fyZfi0f5yQsNmRL_lP"
        link="https://blackbox.ai"
      />
    </div>
  );
}
